name: Build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodule
        run: git submodule update --init

      - name: Change submodule branch
        run: |
          cd Radiance
          git checkout master
          cd ..

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.2
        # to supply options, put them in 'env', like:
        env:
          CIBW_SKIP: pp* cp*musllinux* cp*-macosx_x86*

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
